### ISSUE TITLE
Why OutputBitStream all fixed capacity ?

### ISSUE THREAD

**Issue by huang-jesse** [Spatio-Temporal-Lab/elf#43]
Should I know why OutputBitStream has a fixed capacity?

For example:
```
out = new OutputBitStream(new byte[10000]);
```

Can i just put another size for it?

**Comment by huang-jesse** [comment]
What is this `System.out.println(compressor.getSize());` mean, is it `compressed size` ?

**Comment by IrisLoveLeo** [comment]
Thank you for your question. It means the maximum compressed size. We use the fixed capacity just for easy of implementation, for experiments only.
